// <auto-generated />
namespace sReportsV2.Domain.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitImpressum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitImpressum));
        
        string IMigrationMetadata.Id
        {
            get { return "202210111516486_InitImpressum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
