namespace sReportsV2.Domain.Sql.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddCreatedByToEntity : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Addresses", "CreatedById", c => c.Int());
            AddColumn("dbo.ChemotherapySchemaInstances", "CreatedById", c => c.Int());
            AddColumn("dbo.ChemotherapySchemas", "CreatedById", c => c.Int());
            AddColumn("dbo.Users", "CreatedById", c => c.Int());
            AddColumn("dbo.UserAcademicPositions", "CreatedById", c => c.Int());
            AddColumn("dbo.Organizations", "CreatedById", c => c.Int());
            AddColumn("dbo.OrganizationClinicalDomains", "CreatedById", c => c.Int());
            AddColumn("dbo.OrganizationRelations", "CreatedById", c => c.Int());
            AddColumn("dbo.Telecoms", "CreatedById", c => c.Int());
            AddColumn("dbo.UserRoles", "CreatedById", c => c.Int());
            AddColumn("dbo.Roles", "CreatedById", c => c.Int());
            AddColumn("dbo.Medications", "CreatedById", c => c.Int());
            AddColumn("dbo.ChemotherapySchemaInstanceVersions", "CreatedById", c => c.Int());
            AddColumn("dbo.MedicationReplacements", "CreatedById", c => c.Int());
            AddColumn("dbo.MedicationInstances", "CreatedById", c => c.Int());
            AddColumn("dbo.SmartOncologyPatients", "CreatedById", c => c.Int());
            AddColumn("dbo.EpisodeOfCares", "CreatedById", c => c.Int());
            AddColumn("dbo.Comments", "CreatedById", c => c.Int());
            AddColumn("dbo.CustomEnums", "CreatedById", c => c.Int());
            AddColumn("dbo.ThesaurusEntries", "CreatedById", c => c.Int());
            AddColumn("dbo.Encounters", "CreatedById", c => c.Int());
            AddColumn("dbo.GlobalThesaurusRoles", "CreatedById", c => c.Int());
            AddColumn("dbo.GlobalThesaurusUserRoles", "CreatedById", c => c.Int());
            AddColumn("dbo.GlobalThesaurusUsers", "CreatedById", c => c.Int());
            AddColumn("dbo.OutsideUsers", "CreatedById", c => c.Int());
            AddColumn("dbo.Patients", "CreatedById", c => c.Int());
            AddColumn("dbo.PatientAddresses", "CreatedById", c => c.Int());
            AddColumn("dbo.PatientTelecoms", "CreatedById", c => c.Int());
            AddColumn("dbo.ThesaurusMerges", "CreatedById", c => c.Int());
            CreateIndex("dbo.Addresses", "CreatedById");
            CreateIndex("dbo.Users", "CreatedById");
            CreateIndex("dbo.UserAcademicPositions", "CreatedById");
            CreateIndex("dbo.Organizations", "CreatedById");
            CreateIndex("dbo.OrganizationClinicalDomains", "CreatedById");
            CreateIndex("dbo.OrganizationRelations", "CreatedById");
            CreateIndex("dbo.Telecoms", "CreatedById");
            CreateIndex("dbo.UserRoles", "CreatedById");
            CreateIndex("dbo.Roles", "CreatedById");
            CreateIndex("dbo.ChemotherapySchemaInstances", "CreatedById");
            CreateIndex("dbo.ChemotherapySchemas", "CreatedById");
            CreateIndex("dbo.Medications", "CreatedById");
            CreateIndex("dbo.ChemotherapySchemaInstanceVersions", "CreatedById");
            CreateIndex("dbo.MedicationReplacements", "CreatedById");
            CreateIndex("dbo.MedicationInstances", "CreatedById");
            CreateIndex("dbo.SmartOncologyPatients", "CreatedById");
            CreateIndex("dbo.EpisodeOfCares", "CreatedById");
            CreateIndex("dbo.Comments", "CreatedById");
            CreateIndex("dbo.CustomEnums", "CreatedById");
            CreateIndex("dbo.ThesaurusEntries", "CreatedById");
            CreateIndex("dbo.Encounters", "CreatedById");
            CreateIndex("dbo.GlobalThesaurusRoles", "CreatedById");
            CreateIndex("dbo.GlobalThesaurusUserRoles", "CreatedById");
            CreateIndex("dbo.GlobalThesaurusUsers", "CreatedById");
            CreateIndex("dbo.OutsideUsers", "CreatedById");
            CreateIndex("dbo.Patients", "CreatedById");
            CreateIndex("dbo.PatientAddresses", "CreatedById");
            CreateIndex("dbo.PatientTelecoms", "CreatedById");
            CreateIndex("dbo.ThesaurusMerges", "CreatedById");
            AddForeignKey("dbo.UserAcademicPositions", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.Users", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.OrganizationClinicalDomains", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.Organizations", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.OrganizationRelations", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.Telecoms", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.UserRoles", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.Roles", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.Addresses", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.ChemotherapySchemas", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.Medications", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.ChemotherapySchemaInstanceVersions", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.ChemotherapySchemaInstances", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.MedicationReplacements", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.MedicationInstances", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.SmartOncologyPatients", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.EpisodeOfCares", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.Comments", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.CustomEnums", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.ThesaurusEntries", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.Encounters", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.GlobalThesaurusRoles", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.GlobalThesaurusUserRoles", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.GlobalThesaurusUsers", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.OutsideUsers", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.PatientAddresses", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.Patients", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.PatientTelecoms", "CreatedById", "dbo.Users", "Id");
            AddForeignKey("dbo.ThesaurusMerges", "CreatedById", "dbo.Users", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ThesaurusMerges", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.PatientTelecoms", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.Patients", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.PatientAddresses", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.OutsideUsers", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.GlobalThesaurusUsers", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.GlobalThesaurusUserRoles", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.GlobalThesaurusRoles", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.Encounters", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.ThesaurusEntries", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.CustomEnums", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.Comments", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.EpisodeOfCares", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.SmartOncologyPatients", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.MedicationInstances", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.MedicationReplacements", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.ChemotherapySchemaInstances", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.ChemotherapySchemaInstanceVersions", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.Medications", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.ChemotherapySchemas", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.Addresses", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.Roles", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.UserRoles", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.Telecoms", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.OrganizationRelations", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.Organizations", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.OrganizationClinicalDomains", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.Users", "CreatedById", "dbo.Users");
            DropForeignKey("dbo.UserAcademicPositions", "CreatedById", "dbo.Users");
            DropIndex("dbo.ThesaurusMerges", new[] { "CreatedById" });
            DropIndex("dbo.PatientTelecoms", new[] { "CreatedById" });
            DropIndex("dbo.PatientAddresses", new[] { "CreatedById" });
            DropIndex("dbo.Patients", new[] { "CreatedById" });
            DropIndex("dbo.OutsideUsers", new[] { "CreatedById" });
            DropIndex("dbo.GlobalThesaurusUsers", new[] { "CreatedById" });
            DropIndex("dbo.GlobalThesaurusUserRoles", new[] { "CreatedById" });
            DropIndex("dbo.GlobalThesaurusRoles", new[] { "CreatedById" });
            DropIndex("dbo.Encounters", new[] { "CreatedById" });
            DropIndex("dbo.ThesaurusEntries", new[] { "CreatedById" });
            DropIndex("dbo.CustomEnums", new[] { "CreatedById" });
            DropIndex("dbo.Comments", new[] { "CreatedById" });
            DropIndex("dbo.EpisodeOfCares", new[] { "CreatedById" });
            DropIndex("dbo.SmartOncologyPatients", new[] { "CreatedById" });
            DropIndex("dbo.MedicationInstances", new[] { "CreatedById" });
            DropIndex("dbo.MedicationReplacements", new[] { "CreatedById" });
            DropIndex("dbo.ChemotherapySchemaInstanceVersions", new[] { "CreatedById" });
            DropIndex("dbo.Medications", new[] { "CreatedById" });
            DropIndex("dbo.ChemotherapySchemas", new[] { "CreatedById" });
            DropIndex("dbo.ChemotherapySchemaInstances", new[] { "CreatedById" });
            DropIndex("dbo.Roles", new[] { "CreatedById" });
            DropIndex("dbo.UserRoles", new[] { "CreatedById" });
            DropIndex("dbo.Telecoms", new[] { "CreatedById" });
            DropIndex("dbo.OrganizationRelations", new[] { "CreatedById" });
            DropIndex("dbo.OrganizationClinicalDomains", new[] { "CreatedById" });
            DropIndex("dbo.Organizations", new[] { "CreatedById" });
            DropIndex("dbo.UserAcademicPositions", new[] { "CreatedById" });
            DropIndex("dbo.Users", new[] { "CreatedById" });
            DropIndex("dbo.Addresses", new[] { "CreatedById" });
            DropColumn("dbo.ThesaurusMerges", "CreatedById");
            DropColumn("dbo.PatientTelecoms", "CreatedById");
            DropColumn("dbo.PatientAddresses", "CreatedById");
            DropColumn("dbo.Patients", "CreatedById");
            DropColumn("dbo.OutsideUsers", "CreatedById");
            DropColumn("dbo.GlobalThesaurusUsers", "CreatedById");
            DropColumn("dbo.GlobalThesaurusUserRoles", "CreatedById");
            DropColumn("dbo.GlobalThesaurusRoles", "CreatedById");
            DropColumn("dbo.Encounters", "CreatedById");
            DropColumn("dbo.ThesaurusEntries", "CreatedById");
            DropColumn("dbo.CustomEnums", "CreatedById");
            DropColumn("dbo.Comments", "CreatedById");
            DropColumn("dbo.EpisodeOfCares", "CreatedById");
            DropColumn("dbo.SmartOncologyPatients", "CreatedById");
            DropColumn("dbo.MedicationInstances", "CreatedById");
            DropColumn("dbo.MedicationReplacements", "CreatedById");
            DropColumn("dbo.ChemotherapySchemaInstanceVersions", "CreatedById");
            DropColumn("dbo.Medications", "CreatedById");
            DropColumn("dbo.Roles", "CreatedById");
            DropColumn("dbo.UserRoles", "CreatedById");
            DropColumn("dbo.Telecoms", "CreatedById");
            DropColumn("dbo.OrganizationRelations", "CreatedById");
            DropColumn("dbo.OrganizationClinicalDomains", "CreatedById");
            DropColumn("dbo.Organizations", "CreatedById");
            DropColumn("dbo.UserAcademicPositions", "CreatedById");
            DropColumn("dbo.Users", "CreatedById");
            DropColumn("dbo.ChemotherapySchemas", "CreatedById");
            DropColumn("dbo.ChemotherapySchemaInstances", "CreatedById");
            DropColumn("dbo.Addresses", "CreatedById");
        }
    }
}
